// Versioned local playtest catalog. All 96 drawings have a declared mechanic.
export const CONTENT_VERSION = 'yard-content-2';
const EXPANDED_ITEMS = {
  17: ['magnet','greed',{duration:100,radius:760,speedCost:7},'Sweep up existing unclaimed coins within 760 units for 5 seconds; movement is 7 slower. No coins are created.'],
  18: ['snare','sabotage',{range:1100,slow:35,selfSlow:20},'Clamp the nearest opponent within 1100 units: slow them for 1.75 seconds and yourself for 1 second. Step outside its reach during setup.'],
  20: ['reach','scavenge',{duration:100,reach:170,powerCost:1},'Extend attack reach by 170 for 5 seconds, at the cost of 1 damage. The tape never changes the hitbox.'],
  21: ['perch','range',{duration:100,reach:210,speedCost:12,protection:0},'Gain 210 attack reach for 5 seconds while moving 12 slower; close the gap during recovery.'],
  22: ['snip','defense',{},'After a quick 0.2-second setup, cut off active slow and gain 2 seconds of slow-zone re-entry immunity. Does nothing when already moving freely; cannot restore health or end a committed roll.'],
  25: ['alert','caution',{duration:120,bonus:25,kind:'hazard'},'For 6 seconds, react 25 points more often to already visible floor warnings. Grants no private future information or damage resistance.'],
  27: ['focus','caution',{duration:140},'Ignore distracting decoys for 7 seconds. Headphones do not block attacks or alter essential visual warnings.'],
  28: ['magnet','greed',{duration:140,radius:610,speedCost:0},'Collect existing unclaimed coins within 610 units for 7 seconds. No extra coins, ownership transfers or hidden locations.'],
  29: ['brace','defense',{duration:120,reduction:2,speedCost:5},'During attack windup, reduce each hit by 2 for 6 seconds; movement is 5 slower. Every hit still deals at least 1.'],
  30: ['alert','counter',{duration:120,bonus:25,kind:'attack'},'For 6 seconds, react 25 points more often to visible incoming attacks. It improves a dodge attempt, never guarantees escape.'],
  31: ['read','counter',{duration:120,bonus:12,counter:10},'For 6 seconds, add 12 points to warning reactions and extend earned counter openings by half a second. No opening is granted without a successful evade.'],
  32: ['mark','opportunism',{duration:100,range:2200,bonus:100},'Focus the nearest visible opponent for 5 seconds, adding 100 to that pursuit score. They can lead the wearer away from coins; no target means no effect.'],
  34: ['taunt','defense',{duration:100,shield:1,bonus:80},'Gain one protection charge, but nearby opponents favor pursuing this conspicuous crown for 5 seconds. No immunity or damage bonus.'],
  35: ['feint','aggression',{duration:100,windup:3,power:1},'For 5 seconds, attacks gain 1 damage but take 3 extra ticks to wind up. Opponents can leave the marked strike point.'],
  41: ['parry','defense',{duration:120,charges:1,threshold:7,reduction:4,speedCost:0,busy:0},'Parry one attack of 7 damage or less, reducing it by 4, within 6 seconds. Heavy hits bypass the candy; minimum damage remains 1.'],
  43: ['tempo','counter',{duration:100,windup:3,recovery:4},'For 5 seconds, wait 3 extra ticks before striking, then recover 4 ticks faster. Recovery never drops below 4 ticks.'],
  44: ['anchor','defense',{duration:120,factor:35,speedCost:4},'For 6 seconds, receive only 35 percent of shove distance, but move 4 slower. Damage and ordinary movement remain otherwise unchanged.'],
  48: ['shove','mobility',{range:1100,push:260,recoil:130},'After setup, push the nearest opponent up to 260 units and recoil 130 units. Walls can stop either movement; causes no direct damage.'],
  50: ['projectile','sabotage',{range:1800,radius:360,delay:20,damage:3,push:260},'Send a reel at one marked point after a 1-second floor warning: 3 damage and up to 260 shove within 360 units. Anyone can leave the marked area.'],
  51: ['escort','mobility',{duration:100,speed:9,powerCost:1,shield:1},'Gain one guard charge and move 9 faster for 5 seconds, but attack for 1 less damage while pushing the trolley.'],
  53: ['projectile','sabotage',{range:1900,radius:330,delay:24,damage:2,push:230},'Dispatch a toy to a fixed marked point: after 1.2 seconds it deals 2 damage and shoves up to 230 units within 330. It does not chase a moving target.'],
  54: ['platform','defense',{duration:100,radius:680,reduction:1,speedCost:7},'Raise a marked work platform for 5 seconds. Anyone inside takes 1 less damage but moves 7 slower. The platform does not grant ownership or trap fighters.'],
  55: ['projectile','sabotage',{range:1600,radius:450,delay:22,damage:2,push:350},'Roll a pipe toward a fixed marked area. After 1.1 seconds it deals 2 damage and shoves up to 350 units; step outside its 450-unit radius.'],
  56: ['rush','mobility',{duration:24,shield:1},'Gain one guard charge and commit to a straight 1.2-second roll. No attacks or pickups during the roll; terrain can stop movement.'],
  59: ['coin-snare','greed',{range:1800,count:3,slow:20},'Pull up to three existing unclaimed coins to the user, then slow their feet for 1 second. It cannot take banked coins or increase the fixed budget.'],
  65: ['pulse-zone','sabotage',{duration:120,radius:630,period:40,on:12,slow:12},'Create a visible traction patch for 6 seconds. It pulses for 12 ticks every 40; crossing during a pulse slows feet for 12 ticks, with re-entry immunity.'],
  69: ['snare','sabotage',{range:1300,slow:25,selfSlow:12},'Snag the nearest opponent within 1300 for 1.25 seconds, slowing the user for 0.6 seconds too. No damage, stolen equipment or permanent restraint.'],
  71: ['fake','novelty',{duration:100},'Place a visibly fake wooden-coin lure for 5 seconds. An opponent with greed above 60 may lose 8 ticks inspecting it. It is never a funded coin.'],
  76: ['projectile','sabotage',{range:1600,radius:650,delay:24,damage:1,push:240},'Mark a foam-beam landing for 1.2 seconds. Occupants take 1 damage and move up to 240 units outward; leave the large shadow before it falls.'],
  77: ['projectile','sabotage',{range:2200,radius:300,delay:20,damage:5,push:120},'Launch a light prop toward a fixed point after a 1-second warning: 5 damage and a 120-unit shove within 300 units. Setup is interruptible.'],
  79: ['barricade','cover',{duration:80,radius:520,slow:16,shield:1},'Unfold a temporary rough crossing and gain one guard charge. Anyone crossing its 520-unit patch slows for 16 ticks; it lasts 4 seconds.'],
  81: ['beacon','caution',{duration:120,radius:1100,bonus:20},'Light a visible 1100-unit work area for 6 seconds. Anyone inside gains 20 points of reaction chance to existing warnings, including opponents.'],
  82: ['parry','defense',{duration:160,charges:2,threshold:9,reduction:3,speedCost:8,busy:0},'Block up to two attacks of 9 damage or less within 8 seconds, reducing each by 3. Carrying the foam slows movement by 8.'],
  85: ['door','sabotage',{range:1300,push:280,stink:60},'Swing the toilet door after setup, shoving the nearest opponent up to 280 units. The operator gains a 3-second stink deterrent and its 2-damage attack penalty.'],
  86: ['perch','defense',{duration:100,reach:180,speedCost:14,protection:1},'Use scaffold footing for 5 seconds: 180 more reach and 1 less incoming damage, but movement is 14 slower. Protection never cancels a hit.'],
  89: ['shove','sabotage',{range:1200,push:330,recoil:0},'Push a gate after setup to shove the nearest opponent up to 330 units. No direct damage; moving outside 1200 units or into safe cover counters it.'],
  92: ['anchor','defense',{duration:160,factor:60,speedCost:2},'For 8 seconds, shove distance is reduced to 60 percent, at a movement cost of 2. The shirt does not prevent damage or change the avatar hitbox.'],
  93: ['parry','defense',{duration:140,charges:1,threshold:9,reduction:5,speedCost:0,busy:4},'Catch one attack of 9 damage or less within 7 seconds, reducing it by 5. Clearing the jacket adds 4 recovery ticks when the catch is used.'],
  94: ['dustguard','defense',{duration:160,charges:2,reduction:4},'For 8 seconds, reduce the next two dust or site impacts by 4. Direct attacks bypass the hat; every impact still deals at least 1.'],
  95: ['charge','aggression',{duration:120,push:180,windup:3},'For 6 seconds, landed attacks add 180 shove distance without increasing damage. Each attack winds up 3 ticks longer; terrain and braced gear can limit the push.'],
};
export const NEW_ITEM_TYPES = Object.freeze(Object.keys(EXPANDED_ITEMS).map(Number));
export const ITEMS = Object.freeze([
  {
    "name": "Shed",
    "tag": "SHELTER",
    "color": "#397954",
    "detail": "For affiliated fighters. Reduces each hit by 5 while hiding, for up to 5.5 seconds. A hit ends the hiding.",
    "art": 0,
    "enabled": true,
    "effect": "shelter",
    "preference": "cover",
    "param": 0,
    "draftId": 1
  },
  {
    "name": "Tool rack",
    "tag": "WEAPON",
    "color": "#b35817",
    "detail": "Equip a mallet: hit for 6–9 instead of 4–7. Replaces wheels.",
    "art": 1,
    "enabled": true,
    "effect": "weapon",
    "preference": "scavenge",
    "param": 0,
    "draftId": 2
  },
  {
    "name": "Mystery crate",
    "tag": "GOOD / BAD?",
    "color": "#8851a6",
    "detail": "Restore up to 18 health or take a 15-point hit. Protection can soften the hit.",
    "art": 2,
    "enabled": true,
    "effect": "chest",
    "preference": "chest",
    "param": 18,
    "draftId": 3
  },
  {
    "name": "Red chair",
    "tag": "PROTECTION",
    "color": "#24799e",
    "detail": "Refill protection to 3 charges. Each charge blocks up to 6 damage from one hit; at least 1 still gets through.",
    "art": 3,
    "enabled": true,
    "effect": "guard",
    "preference": "defense",
    "param": 3,
    "draftId": 81
  },
  {
    "name": "Blue chair",
    "tag": "PROTECTION",
    "color": "#24799e",
    "detail": "Refill protection to 3 charges. Each charge blocks up to 6 damage from one hit; at least 1 still gets through.",
    "art": 4,
    "enabled": true,
    "effect": "guard",
    "preference": "defense",
    "param": 3,
    "draftId": 81
  },
  {
    "name": "Pallet",
    "tag": "PROTECTION",
    "color": "#24799e",
    "detail": "Pick up protection, not a hiding spot: refill to 3 hit charges. Attacks can still reach you.",
    "art": 5,
    "enabled": true,
    "effect": "guard",
    "preference": "defense",
    "param": 3,
    "draftId": 59
  },
  {
    "name": "Wheelbarrow",
    "tag": "SPEED",
    "color": "#246ca7",
    "detail": "Take the wheels: move about 17% faster. Replaces the mallet, so hit power returns to 4–7.",
    "art": 6,
    "enabled": true,
    "effect": "wheels",
    "preference": "mobility",
    "param": 0,
    "draftId": 41
  },
  {
    "name": "Traffic cone",
    "tag": "TRIP HAZARD",
    "color": "#b93631",
    "detail": "A 7-point trip hit. Protection can soften it. Watch where you are going.",
    "art": 7,
    "enabled": true,
    "effect": "trip",
    "preference": "novelty",
    "param": 7,
    "draftId": 67
  },
  {
    "name": "Mallet",
    "tag": "WEAPON",
    "color": "#b35817",
    "detail": "Equip a mallet: hit for 6–9 instead of 4–7. Replaces wheels.",
    "art": 8,
    "enabled": true,
    "effect": "weapon",
    "preference": "scavenge",
    "param": 0,
    "draftId": 11
  },
  {
    "name": "Tires",
    "tag": "PROTECTION",
    "color": "#24799e",
    "detail": "Refill protection to 3 charges. Each charge blocks up to 6 damage from one hit; at least 1 still gets through.",
    "art": 9,
    "enabled": true,
    "effect": "guard",
    "preference": "defense",
    "param": 3,
    "draftId": 8
  },
  {
    "name": "Boombox",
    "tag": "JUST MUSIC",
    "color": "#74539e",
    "detail": "A tiny dance break. No health, power or speed bonus.",
    "art": 10,
    "enabled": true,
    "effect": "music",
    "preference": "novelty",
    "param": 0,
    "draftId": null
  },
  {
    "name": "Cooler",
    "tag": "GOOD / BAD?",
    "color": "#8851a6",
    "detail": "Restore up to 18 health or take a 15-point hit. Protection can soften the hit.",
    "art": 11,
    "enabled": true,
    "effect": "chest",
    "preference": "chest",
    "param": 18,
    "draftId": 3
  },
  {
    "name": "Block chainsaw",
    "art": 12,
    "pack": "A",
    "slot": 0,
    "draftId": 12,
    "enabled": true,
    "effect": "weapon",
    "param": 1,
    "preference": "scavenge",
    "tag": "WEAPON",
    "color": "#b35817",
    "detail": "Heavy straight shove. 5–8 power, longer windup and recovery. Replaces your current tool."
  },
  {
    "name": "Shovel that scoops air",
    "art": 13,
    "pack": "A",
    "slot": 1,
    "draftId": 13,
    "enabled": true,
    "effect": "weapon",
    "param": 2,
    "preference": "scavenge",
    "tag": "WEAPON",
    "color": "#b35817",
    "detail": "Longer reach, 4–7 power. A planted swing needs recovery. Replaces your current tool."
  },
  {
    "name": "Overloaded paint roller",
    "art": 14,
    "pack": "A",
    "slot": 2,
    "draftId": 14,
    "enabled": true,
    "effect": "weapon",
    "param": 3,
    "preference": "sabotage",
    "tag": "WEAPON",
    "color": "#b35817",
    "detail": "4–6 power. A landed swipe leaves a small slow patch. Replaces your current tool."
  },
  {
    "name": "Rubber plunger",
    "art": 15,
    "pack": "A",
    "slot": 3,
    "draftId": 15,
    "enabled": true,
    "effect": "weapon",
    "param": 4,
    "preference": "counter",
    "tag": "WEAPON",
    "color": "#b35817",
    "detail": "3–5 power. A landed hit briefly slows both fighters. Replaces your current tool."
  },
  {
    "name": "Adjustable spanner",
    "art": 16,
    "pack": "A",
    "slot": 4,
    "draftId": 16,
    "enabled": true,
    "effect": "weapon",
    "param": 5,
    "preference": "aggression",
    "tag": "WEAPON",
    "color": "#b35817",
    "detail": "4–6 power with a short windup and short reach. Replaces your current tool."
  },
  {
    "name": "Magnetic sweeper",
    "art": 17,
    "pack": "A",
    "slot": 5,
    "draftId": 17,
    "enabled": false,
    "effect": null,
    "param": 0,
    "preference": "novelty",
    "tag": "ART STUDY",
    "color": "#397954",
    "detail": "Artwork ready for review. This object is not included in matches until its interaction and counters are implemented."
  },
  {
    "name": "Oversized clamp",
    "art": 18,
    "pack": "A",
    "slot": 6,
    "draftId": 18,
    "enabled": false,
    "effect": null,
    "param": 0,
    "preference": "novelty",
    "tag": "ART STUDY",
    "color": "#397954",
    "detail": "Artwork ready for review. This object is not included in matches until its interaction and counters are implemented."
  },
  {
    "name": "Cone on a stick",
    "art": 19,
    "pack": "A",
    "slot": 7,
    "draftId": 19,
    "enabled": true,
    "effect": "weapon",
    "param": 6,
    "preference": "range",
    "tag": "WEAPON",
    "color": "#b35817",
    "detail": "3–5 power, longer reach and a small push. Replaces your current tool."
  },
  {
    "name": "Runaway measuring tape",
    "art": 20,
    "pack": "A",
    "slot": 8,
    "draftId": 20,
    "enabled": false,
    "effect": null,
    "param": 0,
    "preference": "novelty",
    "tag": "ART STUDY",
    "color": "#397954",
    "detail": "Artwork ready for review. This object is not included in matches until its interaction and counters are implemented."
  },
  {
    "name": "Folding ladder",
    "art": 21,
    "pack": "A",
    "slot": 9,
    "draftId": null,
    "enabled": false,
    "effect": null,
    "param": 0,
    "preference": "novelty",
    "tag": "ART STUDY",
    "color": "#397954",
    "detail": "Artwork ready for review. This object is not included in matches until its interaction and counters are implemented."
  },
  {
    "name": "Safety scissors",
    "art": 22,
    "pack": "A",
    "slot": 10,
    "draftId": null,
    "enabled": false,
    "effect": null,
    "param": 0,
    "preference": "novelty",
    "tag": "ART STUDY",
    "color": "#397954",
    "detail": "Artwork ready for review. This object is not included in matches until its interaction and counters are implemented."
  },
  {
    "name": "Squeegee",
    "art": 23,
    "pack": "A",
    "slot": 11,
    "draftId": 70,
    "enabled": true,
    "effect": "wash",
    "param": 0,
    "preference": "caution",
    "tag": "WASH",
    "color": "#397954",
    "detail": "Clear your stink and slow effects and nearby spent floor patches. A short cleanup pause leaves you open."
  },
  {
    "name": "Red beverage helmet",
    "art": 24,
    "pack": "B",
    "slot": 0,
    "draftId": 21,
    "enabled": true,
    "effect": "guard",
    "param": 2,
    "preference": "defense",
    "tag": "GUARD",
    "color": "#24799e",
    "detail": "Two protection charges. Putting it on takes a moment; each charge softens one hit. Local equipment study."
  },
  {
    "name": "Radioactive cap",
    "art": 25,
    "pack": "B",
    "slot": 1,
    "draftId": 22,
    "enabled": false,
    "effect": null,
    "param": 0,
    "preference": "novelty",
    "tag": "ART STUDY",
    "color": "#397954",
    "detail": "Artwork ready for review. This object is not included in matches until its interaction and counters are implemented."
  },
  {
    "name": "Viking helmet",
    "art": 26,
    "pack": "B",
    "slot": 2,
    "draftId": 23,
    "enabled": true,
    "effect": "guard",
    "param": 1,
    "preference": "defense",
    "tag": "GUARD",
    "color": "#24799e",
    "detail": "One protection charge. No damage bonus and no larger hitbox. Local guard study; directional blocking is not active."
  },
  {
    "name": "Headphones",
    "art": 27,
    "pack": "B",
    "slot": 3,
    "draftId": 24,
    "enabled": false,
    "effect": null,
    "param": 0,
    "preference": "novelty",
    "tag": "ART STUDY",
    "color": "#397954",
    "detail": "Artwork ready for review. This object is not included in matches until its interaction and counters are implemented."
  },
  {
    "name": "Coin glasses",
    "art": 28,
    "pack": "B",
    "slot": 4,
    "draftId": 25,
    "enabled": false,
    "effect": null,
    "param": 0,
    "preference": "novelty",
    "tag": "ART STUDY",
    "color": "#397954",
    "detail": "Artwork ready for review. This object is not included in matches until its interaction and counters are implemented."
  },
  {
    "name": "Pirate eye patch",
    "art": 29,
    "pack": "B",
    "slot": 5,
    "draftId": 26,
    "enabled": false,
    "effect": null,
    "param": 0,
    "preference": "novelty",
    "tag": "ART STUDY",
    "color": "#397954",
    "detail": "Artwork ready for review. This object is not included in matches until its interaction and counters are implemented."
  },
  {
    "name": "Red mirror glasses",
    "art": 30,
    "pack": "B",
    "slot": 6,
    "draftId": 27,
    "enabled": false,
    "effect": null,
    "param": 0,
    "preference": "novelty",
    "tag": "ART STUDY",
    "color": "#397954",
    "detail": "Artwork ready for review. This object is not included in matches until its interaction and counters are implemented."
  },
  {
    "name": "Green matrix glasses",
    "art": 31,
    "pack": "B",
    "slot": 7,
    "draftId": 28,
    "enabled": false,
    "effect": null,
    "param": 0,
    "preference": "novelty",
    "tag": "ART STUDY",
    "color": "#397954",
    "detail": "Artwork ready for review. This object is not included in matches until its interaction and counters are implemented."
  },
  {
    "name": "Yellow heart glasses",
    "art": 32,
    "pack": "B",
    "slot": 8,
    "draftId": 29,
    "enabled": false,
    "effect": null,
    "param": 0,
    "preference": "novelty",
    "tag": "ART STUDY",
    "color": "#397954",
    "detail": "Artwork ready for review. This object is not included in matches until its interaction and counters are implemented."
  },
  {
    "name": "Bucket hat",
    "art": 33,
    "pack": "B",
    "slot": 9,
    "draftId": 30,
    "enabled": true,
    "effect": "guard",
    "param": 1,
    "preference": "defense",
    "tag": "GUARD",
    "color": "#24799e",
    "detail": "One protection charge; no attack boost. Local guard study."
  },
  {
    "name": "Orange coin crown",
    "art": 34,
    "pack": "B",
    "slot": 10,
    "draftId": 84,
    "enabled": false,
    "effect": null,
    "param": 0,
    "preference": "novelty",
    "tag": "ART STUDY",
    "color": "#397954",
    "detail": "Artwork ready for review. This object is not included in matches until its interaction and counters are implemented."
  },
  {
    "name": "Moon-and-stars cap",
    "art": 35,
    "pack": "B",
    "slot": 11,
    "draftId": 85,
    "enabled": false,
    "effect": null,
    "param": 0,
    "preference": "novelty",
    "tag": "ART STUDY",
    "color": "#397954",
    "detail": "Artwork ready for review. This object is not included in matches until its interaction and counters are implemented."
  },
  {
    "name": "Gray rabbit plush",
    "art": 36,
    "pack": "C",
    "slot": 0,
    "draftId": 31,
    "enabled": true,
    "effect": "decoy",
    "param": 0,
    "preference": "novelty",
    "tag": "DECOY",
    "color": "#397954",
    "detail": "Place a visible plush decoy for 4 seconds. Curious fighters may waste a short pause investigating. It is never counted as a fighter."
  },
  {
    "name": "Hamburger",
    "art": 37,
    "pack": "C",
    "slot": 1,
    "draftId": 32,
    "enabled": true,
    "effect": "food",
    "param": 30,
    "preference": "caution",
    "tag": "FOOD",
    "color": "#397954",
    "detail": "Restore up to 30 stamina after a short eating pause. No health gain; attacks spend stamina."
  },
  {
    "name": "Coffee time mug",
    "art": 38,
    "pack": "C",
    "slot": 2,
    "draftId": 33,
    "enabled": true,
    "effect": "coffee",
    "param": 120,
    "preference": "mobility",
    "tag": "COFFEE",
    "color": "#397954",
    "detail": "After a sip, attack recovery is shorter for 6 seconds. Health and hit power do not increase."
  },
  {
    "name": "Coffee ZONE mug",
    "art": 39,
    "pack": "C",
    "slot": 3,
    "draftId": 34,
    "enabled": true,
    "effect": "heal",
    "param": 10,
    "preference": "cover",
    "tag": "HEAL",
    "color": "#397954",
    "detail": "Rest briefly to recover up to 10 health. One use per fighter; no endless recovery. Local rest-stop study."
  },
  {
    "name": "Tipped beer glass",
    "art": 40,
    "pack": "C",
    "slot": 4,
    "draftId": 35,
    "enabled": true,
    "effect": "slide",
    "param": 0,
    "preference": "sabotage",
    "tag": "SLIDE",
    "color": "#aa4939",
    "detail": "A marked spill causes a short slide. No intoxication bonus. Re-entry immunity prevents a slide chain."
  },
  {
    "name": "Pastel candy stack",
    "art": 41,
    "pack": "C",
    "slot": 5,
    "draftId": 36,
    "enabled": false,
    "effect": null,
    "param": 0,
    "preference": "novelty",
    "tag": "ART STUDY",
    "color": "#397954",
    "detail": "Artwork ready for review. This object is not included in matches until its interaction and counters are implemented."
  },
  {
    "name": "Black TV remote",
    "art": 42,
    "pack": "C",
    "slot": 6,
    "draftId": 37,
    "enabled": true,
    "effect": "trap",
    "param": 6,
    "preference": "sabotage",
    "tag": "TRAP",
    "color": "#aa4939",
    "detail": "Pause to arm a nearby marked danger circle. It hits after a one-second warning, including its operator if still inside."
  },
  {
    "name": "Clock pendant",
    "art": 43,
    "pack": "C",
    "slot": 7,
    "draftId": 38,
    "enabled": false,
    "effect": null,
    "param": 0,
    "preference": "novelty",
    "tag": "ART STUDY",
    "color": "#397954",
    "detail": "Artwork ready for review. This object is not included in matches until its interaction and counters are implemented."
  },
  {
    "name": "Pink clip bow",
    "art": 44,
    "pack": "C",
    "slot": 8,
    "draftId": 39,
    "enabled": false,
    "effect": null,
    "param": 0,
    "preference": "novelty",
    "tag": "ART STUDY",
    "color": "#397954",
    "detail": "Artwork ready for review. This object is not included in matches until its interaction and counters are implemented."
  },
  {
    "name": "Cardboard cat",
    "art": 45,
    "pack": "C",
    "slot": 9,
    "draftId": 40,
    "enabled": true,
    "effect": "decoy",
    "param": 0,
    "preference": "novelty",
    "tag": "DECOY",
    "color": "#397954",
    "detail": "Place a cardboard distraction for 4 seconds. It is visibly a prop, never a fake fighter or an autonomous pet."
  },
  {
    "name": "Tiny white flag",
    "art": 46,
    "pack": "C",
    "slot": 10,
    "draftId": 90,
    "enabled": true,
    "effect": "devotion",
    "param": 0,
    "preference": "devotion",
    "tag": "DEVOTION",
    "color": "#397954",
    "detail": "A two-second vulnerable pause grants six seconds of softer hits taken (2 less) and weaker attacks (1 less). A hit interrupts the pause. Neutral devotion study, without an invented Wossum face or quotation."
  },
  {
    "name": "Complaint clipboard",
    "art": 47,
    "pack": "C",
    "slot": 11,
    "draftId": 83,
    "enabled": true,
    "effect": "guard",
    "param": 2,
    "preference": "defense",
    "tag": "GUARD",
    "color": "#24799e",
    "detail": "Two protection charges after a short pause. No invulnerability. Local guard study."
  },
  {
    "name": "Backward hand truck",
    "art": 48,
    "pack": "D",
    "slot": 0,
    "draftId": 42,
    "enabled": false,
    "effect": null,
    "param": 0,
    "preference": "novelty",
    "tag": "ART STUDY",
    "color": "#397954",
    "detail": "Artwork ready for review. This object is not included in matches until its interaction and counters are implemented."
  },
  {
    "name": "Brick skateboard",
    "art": 49,
    "pack": "D",
    "slot": 1,
    "draftId": 43,
    "enabled": true,
    "effect": "skate",
    "param": 0,
    "preference": "mobility",
    "tag": "SKATE",
    "color": "#397954",
    "detail": "A committed straight roll for one second. No attacking or coin pickup during the roll."
  },
  {
    "name": "Cable reel",
    "art": 50,
    "pack": "D",
    "slot": 2,
    "draftId": 44,
    "enabled": false,
    "effect": null,
    "param": 0,
    "preference": "novelty",
    "tag": "ART STUDY",
    "color": "#397954",
    "detail": "Artwork ready for review. This object is not included in matches until its interaction and counters are implemented."
  },
  {
    "name": "Trolley of bolts",
    "art": 51,
    "pack": "D",
    "slot": 3,
    "draftId": 45,
    "enabled": false,
    "effect": null,
    "param": 0,
    "preference": "novelty",
    "tag": "ART STUDY",
    "color": "#397954",
    "detail": "Artwork ready for review. This object is not included in matches until its interaction and counters are implemented."
  },
  {
    "name": "Office chair",
    "art": 52,
    "pack": "D",
    "slot": 4,
    "draftId": 46,
    "enabled": true,
    "effect": "skate",
    "param": 0,
    "preference": "mobility",
    "tag": "SKATE",
    "color": "#397954",
    "detail": "A committed short roll. No attack or collection until it stops. Local movement study; a curved path is not active."
  },
  {
    "name": "Forklift toy",
    "art": 53,
    "pack": "D",
    "slot": 5,
    "draftId": 47,
    "enabled": false,
    "effect": null,
    "param": 0,
    "preference": "novelty",
    "tag": "ART STUDY",
    "color": "#397954",
    "detail": "Artwork ready for review. This object is not included in matches until its interaction and counters are implemented."
  },
  {
    "name": "Pallet jack",
    "art": 54,
    "pack": "D",
    "slot": 6,
    "draftId": 48,
    "enabled": false,
    "effect": null,
    "param": 0,
    "preference": "novelty",
    "tag": "ART STUDY",
    "color": "#397954",
    "detail": "Artwork ready for review. This object is not included in matches until its interaction and counters are implemented."
  },
  {
    "name": "Concrete pipe roller",
    "art": 55,
    "pack": "D",
    "slot": 7,
    "draftId": 49,
    "enabled": false,
    "effect": null,
    "param": 0,
    "preference": "novelty",
    "tag": "ART STUDY",
    "color": "#397954",
    "detail": "Artwork ready for review. This object is not included in matches until its interaction and counters are implemented."
  },
  {
    "name": "Ladder sled",
    "art": 56,
    "pack": "D",
    "slot": 8,
    "draftId": 50,
    "enabled": false,
    "effect": null,
    "param": 0,
    "preference": "novelty",
    "tag": "ART STUDY",
    "color": "#397954",
    "detail": "Artwork ready for review. This object is not included in matches until its interaction and counters are implemented."
  },
  {
    "name": "Coin conveyor",
    "art": 57,
    "pack": "D",
    "slot": 9,
    "draftId": 78,
    "enabled": true,
    "effect": "coin-route",
    "param": 0,
    "preference": "greed",
    "tag": "COIN ROUTE",
    "color": "#397954",
    "detail": "After a pause, relocate up to three nearby unclaimed coins beside the conveyor. The fixed pickup budget never increases. Local routing study."
  },
  {
    "name": "Cashier tray",
    "art": 58,
    "pack": "D",
    "slot": 10,
    "draftId": 76,
    "enabled": true,
    "effect": "coin-route",
    "param": 0,
    "preference": "greed",
    "tag": "COIN ROUTE",
    "color": "#397954",
    "detail": "After a pause, relocate up to three nearby unclaimed coins beside the tray. Already banked PIT cannot move."
  },
  {
    "name": "Sticky coin mat",
    "art": 59,
    "pack": "D",
    "slot": 11,
    "draftId": 80,
    "enabled": false,
    "effect": null,
    "param": 0,
    "preference": "novelty",
    "tag": "ART STUDY",
    "color": "#397954",
    "detail": "Artwork ready for review. This object is not included in matches until its interaction and counters are implemented."
  },
  {
    "name": "Wet cement patch",
    "art": 60,
    "pack": "E",
    "slot": 0,
    "draftId": 51,
    "enabled": true,
    "effect": "slow",
    "param": 0,
    "preference": "caution",
    "tag": "SLOW",
    "color": "#aa4939",
    "detail": "Marked rough ground slows crossing for one second. It cannot stack and never traps a fighter permanently."
  },
  {
    "name": "Comic puke patch",
    "art": 61,
    "pack": "E",
    "slot": 1,
    "draftId": 52,
    "enabled": true,
    "effect": "stink",
    "param": 120,
    "preference": "stink",
    "tag": "STINK",
    "color": "#aa4939",
    "detail": "Six seconds of visible stink discourage close pursuit, but reduce your hit power by 2. Washing clears it."
  },
  {
    "name": "Rainbow spill",
    "art": 62,
    "pack": "E",
    "slot": 2,
    "draftId": 53,
    "enabled": true,
    "effect": "slide",
    "param": 0,
    "preference": "novelty",
    "tag": "SLIDE",
    "color": "#aa4939",
    "detail": "A short visible slide, with no attack or pickup during it. Re-entry immunity prevents repeated sliding."
  },
  {
    "name": "Oil drip",
    "art": 63,
    "pack": "E",
    "slot": 3,
    "draftId": 54,
    "enabled": true,
    "effect": "slide",
    "param": 0,
    "preference": "sabotage",
    "tag": "SLIDE",
    "color": "#aa4939",
    "detail": "A short visible skid rather than permanent loss of control. Re-entry immunity prevents chains."
  },
  {
    "name": "Blue paint rectangle",
    "art": 64,
    "pack": "E",
    "slot": 4,
    "draftId": 55,
    "enabled": true,
    "effect": "trail",
    "param": 100,
    "preference": "novelty",
    "tag": "TRAIL",
    "color": "#397954",
    "detail": "Leave a blue cosmetic trail for 5 seconds. No hidden combat or ownership change."
  },
  {
    "name": "Analog glitch tarp",
    "art": 65,
    "pack": "E",
    "slot": 5,
    "draftId": 56,
    "enabled": false,
    "effect": null,
    "param": 0,
    "preference": "novelty",
    "tag": "ART STUDY",
    "color": "#397954",
    "detail": "Artwork ready for review. This object is not included in matches until its interaction and counters are implemented."
  },
  {
    "name": "Loose tile stack",
    "art": 66,
    "pack": "E",
    "slot": 6,
    "draftId": 57,
    "enabled": true,
    "effect": "slow",
    "param": 0,
    "preference": "caution",
    "tag": "SLOW",
    "color": "#aa4939",
    "detail": "A rough patch briefly slows you. It never permanently blocks a route. Local floor study."
  },
  {
    "name": "Pea gravel",
    "art": 67,
    "pack": "E",
    "slot": 7,
    "draftId": 58,
    "enabled": true,
    "effect": "slow",
    "param": 0,
    "preference": "caution",
    "tag": "SLOW",
    "color": "#aa4939",
    "detail": "Loose gravel slows crossing briefly. The slow cannot stack. Local floor study."
  },
  {
    "name": "Sandbag seam",
    "art": 68,
    "pack": "E",
    "slot": 8,
    "draftId": 59,
    "enabled": true,
    "effect": "guard",
    "param": 2,
    "preference": "defense",
    "tag": "GUARD",
    "color": "#24799e",
    "detail": "Take two protection charges after a short pause. Attacks can still reach you."
  },
  {
    "name": "Dust sheet",
    "art": 69,
    "pack": "E",
    "slot": 9,
    "draftId": 60,
    "enabled": false,
    "effect": null,
    "param": 0,
    "preference": "novelty",
    "tag": "ART STUDY",
    "color": "#397954",
    "detail": "Artwork ready for review. This object is not included in matches until its interaction and counters are implemented."
  },
  {
    "name": "Poop parcel",
    "art": 70,
    "pack": "E",
    "slot": 10,
    "draftId": 69,
    "enabled": true,
    "effect": "stink",
    "param": 120,
    "preference": "stink",
    "tag": "STINK",
    "color": "#aa4939",
    "detail": "Six seconds of comic stink, but 2 less hit power. Washing clears it. No health or damage bonus."
  },
  {
    "name": "Painted wooden coin",
    "art": 71,
    "pack": "E",
    "slot": 11,
    "draftId": 77,
    "enabled": false,
    "effect": null,
    "param": 0,
    "preference": "novelty",
    "tag": "ART STUDY",
    "color": "#397954",
    "detail": "Artwork ready for review. This object is not included in matches until its interaction and counters are implemented."
  },
  {
    "name": "Seesaw plank",
    "art": 72,
    "pack": "F",
    "slot": 0,
    "draftId": 61,
    "enabled": true,
    "effect": "trap",
    "param": 6,
    "preference": "sabotage",
    "tag": "TRAP",
    "color": "#aa4939",
    "detail": "Arm a small marked bump zone after a pause. One second of warning before impact; anyone inside can be hit. Local trap study."
  },
  {
    "name": "Bucket drop",
    "art": 73,
    "pack": "F",
    "slot": 1,
    "draftId": 62,
    "enabled": true,
    "effect": "trap",
    "param": 5,
    "preference": "sabotage",
    "tag": "TRAP",
    "color": "#aa4939",
    "detail": "A small warning circle precedes a 5-point bucket bump. Its operator is not immune. Local trap study."
  },
  {
    "name": "Paint-can pendulum",
    "art": 74,
    "pack": "F",
    "slot": 2,
    "draftId": 63,
    "enabled": true,
    "effect": "trap",
    "param": 7,
    "preference": "sabotage",
    "tag": "TRAP",
    "color": "#aa4939",
    "detail": "A pause arms a marked 7-point danger circle. Its operator can be hit too. Swinging physics remain a later study."
  },
  {
    "name": "Air hose valve",
    "art": 75,
    "pack": "F",
    "slot": 3,
    "draftId": 64,
    "enabled": true,
    "effect": "trap",
    "param": 5,
    "preference": "sabotage",
    "tag": "TRAP",
    "color": "#aa4939",
    "detail": "A valve arms a marked 5-point danger circle, with a one-second warning and no hidden target tracking."
  },
  {
    "name": "Foam beam",
    "art": 76,
    "pack": "F",
    "slot": 4,
    "draftId": 65,
    "enabled": false,
    "effect": null,
    "param": 0,
    "preference": "novelty",
    "tag": "ART STUDY",
    "color": "#397954",
    "detail": "Artwork ready for review. This object is not included in matches until its interaction and counters are implemented."
  },
  {
    "name": "Warning-tape slingshot",
    "art": 77,
    "pack": "F",
    "slot": 5,
    "draftId": 66,
    "enabled": false,
    "effect": null,
    "param": 0,
    "preference": "novelty",
    "tag": "ART STUDY",
    "color": "#397954",
    "detail": "Artwork ready for review. This object is not included in matches until its interaction and counters are implemented."
  },
  {
    "name": "Springy cone",
    "art": 78,
    "pack": "F",
    "slot": 6,
    "draftId": 67,
    "enabled": true,
    "effect": "trip",
    "param": 7,
    "preference": "novelty",
    "tag": "TRIP",
    "color": "#aa4939",
    "detail": "A 7-point trip hit. Protection softens it. No real injury or elimination override."
  },
  {
    "name": "Folding step stool",
    "art": 79,
    "pack": "F",
    "slot": 7,
    "draftId": 68,
    "enabled": false,
    "effect": null,
    "param": 0,
    "preference": "novelty",
    "tag": "ART STUDY",
    "color": "#397954",
    "detail": "Artwork ready for review. This object is not included in matches until its interaction and counters are implemented."
  },
  {
    "name": "Mixer drum",
    "art": 80,
    "pack": "F",
    "slot": 8,
    "draftId": 97,
    "enabled": true,
    "effect": "trap",
    "param": 7,
    "preference": "sabotage",
    "tag": "TRAP",
    "color": "#aa4939",
    "detail": "Arm a marked 7-point danger circle. Leave during the one-second warning. Local mixer study."
  },
  {
    "name": "Work-light tripod",
    "art": 81,
    "pack": "F",
    "slot": 9,
    "draftId": 98,
    "enabled": false,
    "effect": null,
    "param": 0,
    "preference": "novelty",
    "tag": "ART STUDY",
    "color": "#397954",
    "detail": "Artwork ready for review. This object is not included in matches until its interaction and counters are implemented."
  },
  {
    "name": "Foam bundle",
    "art": 82,
    "pack": "F",
    "slot": 10,
    "draftId": 99,
    "enabled": false,
    "effect": null,
    "param": 0,
    "preference": "novelty",
    "tag": "ART STUDY",
    "color": "#397954",
    "detail": "Artwork ready for review. This object is not included in matches until its interaction and counters are implemented."
  },
  {
    "name": "Cleanup sweeper",
    "art": 83,
    "pack": "F",
    "slot": 11,
    "draftId": 100,
    "enabled": true,
    "effect": "wash",
    "param": 0,
    "preference": "caution",
    "tag": "WASH",
    "color": "#397954",
    "detail": "Wash off stink and slow effects and clear nearby spent floor patches. Banked and unclaimed coin ownership is unchanged."
  },
  {
    "name": "Site office hatch",
    "art": 84,
    "pack": "G",
    "slot": 0,
    "draftId": 5,
    "enabled": true,
    "effect": "guard",
    "param": 2,
    "preference": "cover",
    "tag": "GUARD",
    "color": "#24799e",
    "detail": "Two protection charges after a pause. Local cover study, not a wall that blocks every attack."
  },
  {
    "name": "Portable toilet",
    "art": 85,
    "pack": "G",
    "slot": 1,
    "draftId": 6,
    "enabled": false,
    "effect": null,
    "param": 0,
    "preference": "novelty",
    "tag": "ART STUDY",
    "color": "#397954",
    "detail": "Artwork ready for review. This object is not included in matches until its interaction and counters are implemented."
  },
  {
    "name": "Scaffold bay",
    "art": 86,
    "pack": "G",
    "slot": 2,
    "draftId": 7,
    "enabled": false,
    "effect": null,
    "param": 0,
    "preference": "novelty",
    "tag": "ART STUDY",
    "color": "#397954",
    "detail": "Artwork ready for review. This object is not included in matches until its interaction and counters are implemented."
  },
  {
    "name": "Open skip",
    "art": 87,
    "pack": "G",
    "slot": 3,
    "draftId": 8,
    "enabled": true,
    "effect": "guard",
    "param": 2,
    "preference": "defense",
    "tag": "GUARD",
    "color": "#24799e",
    "detail": "Two protection charges after a pause. Local cover study; thrown-item capture is not active."
  },
  {
    "name": "Tool checkout desk",
    "art": 88,
    "pack": "G",
    "slot": 4,
    "draftId": 9,
    "enabled": true,
    "effect": "weapon",
    "param": 0,
    "preference": "scavenge",
    "tag": "WEAPON",
    "color": "#b35817",
    "detail": "Pause to take a mallet. Replaces the current tool; no invisible reservation or currency purchase."
  },
  {
    "name": "Bent fence gate",
    "art": 89,
    "pack": "G",
    "slot": 5,
    "draftId": 10,
    "enabled": false,
    "effect": null,
    "param": 0,
    "preference": "novelty",
    "tag": "ART STUDY",
    "color": "#397954",
    "detail": "Artwork ready for review. This object is not included in matches until its interaction and counters are implemented."
  },
  {
    "name": "Two chairs",
    "art": 90,
    "pack": "G",
    "slot": 6,
    "draftId": 81,
    "enabled": true,
    "effect": "guard",
    "param": 3,
    "preference": "cover",
    "tag": "GUARD",
    "color": "#24799e",
    "detail": "Refill protection to three hit charges. Local cover study; chairs are not movable walls yet."
  },
  {
    "name": "No second best board",
    "art": 91,
    "pack": "G",
    "slot": 7,
    "draftId": 82,
    "enabled": true,
    "effect": "guard",
    "param": 1,
    "preference": "defense",
    "tag": "GUARD",
    "color": "#24799e",
    "detail": "One protection charge. No guarantee of first place. Local guard study."
  },
  {
    "name": "Orange workshirt",
    "art": 92,
    "pack": "G",
    "slot": 8,
    "draftId": 86,
    "enabled": false,
    "effect": null,
    "param": 0,
    "preference": "novelty",
    "tag": "ART STUDY",
    "color": "#397954",
    "detail": "Artwork ready for review. This object is not included in matches until its interaction and counters are implemented."
  },
  {
    "name": "Purple leopard jacket",
    "art": 93,
    "pack": "G",
    "slot": 9,
    "draftId": 87,
    "enabled": false,
    "effect": null,
    "param": 0,
    "preference": "novelty",
    "tag": "ART STUDY",
    "color": "#397954",
    "detail": "Artwork ready for review. This object is not included in matches until its interaction and counters are implemented."
  },
  {
    "name": "Bamboo coin hat",
    "art": 94,
    "pack": "G",
    "slot": 10,
    "draftId": 88,
    "enabled": false,
    "effect": null,
    "param": 0,
    "preference": "novelty",
    "tag": "ART STUDY",
    "color": "#397954",
    "detail": "Artwork ready for review. This object is not included in matches until its interaction and counters are implemented."
  },
  {
    "name": "Gold-edged shoulder horn",
    "art": 95,
    "pack": "G",
    "slot": 11,
    "draftId": 89,
    "enabled": false,
    "effect": null,
    "param": 0,
    "preference": "novelty",
    "tag": "ART STUDY",
    "color": "#397954",
    "detail": "Artwork ready for review. This object is not included in matches until its interaction and counters are implemented."
  }
].map((item,type)=>{const extra=EXPANDED_ITEMS[type];return Object.freeze(extra?{...item,enabled:true,effect:extra[0],preference:extra[1],param:0,mechanic:Object.freeze(extra[2]),channelTicks:type===22?4:14,introducedIn:CONTENT_VERSION,tag:extra[0].toUpperCase(),detail:extra[3]}:item);}));
export const ACTIVE_TYPES = Object.freeze(ITEMS.flatMap((item,i)=>item.enabled?[i]:[]));
export const WEAPONS = Object.freeze([
  {name:'Mallet',art:8,min:6,max:9,reach:690,windup:9,recovery:12,push:140},
  {name:'Block chainsaw',art:12,min:5,max:8,reach:760,windup:13,recovery:16,push:350},
  {name:'Shovel',art:13,min:4,max:7,reach:830,windup:9,recovery:12,push:220},
  {name:'Paint roller',art:14,min:4,max:6,reach:700,windup:9,recovery:12,push:0,slow:true},
  {name:'Plunger',art:15,min:3,max:5,reach:770,windup:9,recovery:13,push:0,tether:true},
  {name:'Spanner',art:16,min:4,max:6,reach:570,windup:5,recovery:7,push:0},
  {name:'Cone stick',art:19,min:3,max:5,reach:890,windup:9,recovery:12,push:220},
]);
